project:
  type: website
  output-dir: docs

website:
  title: "Mariana Freitas"
  navbar:
    left:
      - icon: envelope
        href: "mailto:marianacfreitas2004@gmail.com"
        aria-label: "Email"
      - icon: linkedin
        href: "https://www.linkedin.com/in/mariana-freitas-680b712b6/"
        aria-label: "LinkedIn"
    right:
      - text: "ğŸŒ"
        menu:
          - text: "PortuguÃªs"
            href: "/"
          - text: "English"
            href: "/en/"
      - href: "#sobre"
        text: Sobre
      - href: "#experiencias"
        text: ExperiÃªncias
      - href: "#eventos"
        text: Eventos e Cursos
      - href: producoes.qmd
        text: ProduÃ§Ãµes

language:
  en:
    title: "Mariana Freitas"
    navbar:
      right:
        - text: "ğŸŒ"
          menu:
            - text: "PortuguÃªs"
              href: "/"
            - text: "English"
              href: "/en/"
        - href: "#about"
          text: About
        - href: "#experience"
          text: Experience
        - href: "#events"
          text: Events and Courses
        - href: productions.qmd
          text: Productions

format:
  html:
    theme: darkly
    toc: true
    css: styles.css
