project:
  type: website
  output-dir: docs

website:
  title: "Mariana Freitas"
  favicon: images/site_icon.png
  navbar:
    left:
      - icon: envelope
        href: "mailto:marianacfreitas2004@gmail.com"
        aria-label: "Email"
      - icon: linkedin
        href: "https://www.linkedin.com/in/mariana-freitas-680b712b6/"
        aria-label: "LinkedIn"
    right:
      - text: "ğŸŒ"
        menu:
          - text: "English"
            href: "/"
          - text: "PortuguÃªs"
            href: "/pt/"
      - href: "#about"
        text: About
      - href: "#experiences"
        text: Experiences
      - href: "#events"
        text: Events and Lectures
      - href: productions.qmd
        text: Scientific Production

language:
  pt:
    title: "Mariana Freitas"
    navbar:
      right:
        - text: "ğŸŒ"
          menu:
            - text: "English"
              href: "/"
            - text: "PortuguÃªs"
              href: "/pt/"
        - href: "#sobre"
          text: Sobre
        - href: "#experiencias"  # Corrected from "#experiences" to match content
          text: ExperiÃªncias
        - href: "#eventos"
          text: Eventos e ParticipaÃ§Ãµes
        - href: producoes.qmd
          text: ProduÃ§Ãµes

format:
  html:
    toc: true
    css: styles.css
